### ISSUE TITLE
Walls/Textures could have outlines to identify them better

### ISSUE THREAD

**Issue by Jeretupp** [WelehoBRUDER/Dungeons-of-Tavaraen#37]
![image](https://user-images.githubusercontent.com/51388255/166070322-86456228-906d-4a4b-abdf-35eb2b1bd3db.png)

Walls could have some sort of outline to actually identify between the tiles that are walls and the ones that are just ground

**Comment by WelehoBRUDER** [comment]
I will try something

**Comment by WelehoBRUDER** [comment]
Will be settled upon the release of patch 1.1.1 soon.

**Comment by kassu11** [comment]
Vois lisää asetuksen, mistä voi päättä seinän värin

**Comment by WelehoBRUDER** [comment]
![image](https://user-images.githubusercontent.com/61124548/166114485-c2d448dc-3aa6-4511-8734-7eae3a075c59.png)
